# @hostname = http://localhost:8080

### 
GET {{hostname}}/users

###
PATCH {{hostname}}/users/64af0e5b5de5d477286521af
Content-Type: application/json

{
    "username":    "GOOSE ON CAPS (updated)"
}

### delete goose
DELETE {{hostname}}/users/64aefe347ed4e9cc4f53b0a4

###

POST {{hostname}}/auth/register
Content-Type: application/json

{
    "email":    "goose@goldilock.io",
    "password": "hithere",
    "username": "that goose from the golden egg"
}

###

POST {{hostname}}/auth/login
Content-Type: application/json

{
    "email":    "goose@goldilock.io",
    "password": "hithere"
}

###

POST {{hostname}}/auth/login
Content-Type: application/json

{
    "email":    "poofy@hello.com",
    "password": "hithere"
}

#### make sure to remove any commas from the last json
POST {{hostname}}/auth/register
Content-Type: application/json

{
    "email":    "poofy@hello.com",
    "password": "hithere",
    "username": "first poofy from backend"
}

###

POST {{hostname}}/auth/register
Content-Type: application/json

{
    "email":    "tendomaya@causewhynot.sure",
    "password": "hithere",
    "username": "this is tendo maya surely"
}

###
GET {{hostname}}/auth-endpoint
Authorization: {{apiKey}}

###